repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: [-l 120]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.2
    hooks:
    -    id: nbqa-black
    -    id: nbqa-isort
